{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nx-cache-server.fullname" . }}
  labels:
    {{- include "nx-cache-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  nx-cache-access-token: {{ required "secrets.nxCacheAccessToken is required when secrets.existingSecret is not set" .Values.secrets.nxCacheAccessToken | quote }}
{{- end }}
